# fly.toml app configuration file generated for pettycash-api on 2023-09-11T10:42:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pettycash-api"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
